Add basic file structure
physiopy/physiopy.github.io pull request #1
Opened 2020-11-12 17:07 UTC by eurunuela

2020-11-12 21:40 UTC, smoia requested changes
Ehm... I think there's a file to check :sweat_smile:

2020-11-12 21:40 UTC, smoia commented on docs/index.md
> +# NeuroImaging PREProcessing toolS (NiPreps)
?

2020-11-13 00:05 UTC, smoia requested changes
Also, could we use a different license (basically the media version of Apache 2.0)?

2020-11-13 00:05 UTC, smoia commented on LICENSE
> +CC0 1.0 Universal
Can you change this license to CC BY 4.0 instead?
It's [here](https://choosealicense.com/licenses/cc-by-4.0/)

2020-11-13 07:48 UTC, eurunuela commented on docs/index.md
> +# NeuroImaging PREProcessing toolS (NiPreps)
Good catch! Haha

2020-11-13 08:18 UTC, smoia approved these changes
AFAIK, LGTM!

2020-11-13 08:40 UTC, eurunuela commented
Merging so @sangfrois can work on it!

2020-11-13 08:40 UTC, merged