Markdown file for OHBM tutorial materials and add to menu.
physiopy/physiopy.github.io pull request #40
Opened 2023-07-14 03:00 UTC by kristinazvolanek

Closes #

## Proposed Changes

  -
  -
  -

## Change Type

- [ ] `bugfix`
- [ ] `refactoring`
- [ ] `infrastructure`
- [ ] `documentation`
- [ ] `other`

## Checklist before review

- [ ] I added everything I wanted to add to this PR.
- [ ] \[Documentation only\] I built the docs locally.
- [ ] My contribution is harmonious with the rest of the code: I'm not introducing repetitions.
- [ ] My code respects the adopted style, especially linting conventions.
- [ ] The title of this PR is explanatory on its own, enough to be understood as part of a changelog.
- [ ] I added or indicated the right labels.

- [ ] I added information regarding the timeline of completion for this PR.

- [ ] Please, comment on my PR while it's a draft and give me feedback on the development!

2023-07-14 03:02 UTC, kristinazvolanek commented
@smoia @m-miedema I think I made a markdown page to add our links to the physiopy site... please review to see if I missed any important information!

2023-07-14 23:23 UTC, smoia commented
@kristinazvolanek did you try to build this locally?
@m-miedema can you have a look?
@goodalse2019 sorry to bother you, but could you check this out too?

2023-07-15 02:38 UTC, goodalse2019 requested changes
If the screenshot I shared with Kristina looks good and then just that space addition in mkdocs this should be good to go!

2023-07-15 02:38 UTC, goodalse2019 commented on mkdocs.yml
> +    -OHBM 2023 Tutorials: ohbm23_tutorials.md
You just need to add a space after the dash and before OHBM for it to correctly catch the section!

2023-07-17 13:21 UTC, smoia approved these changes

2023-07-17 13:21 UTC, merged